- hosts: all
  become: true
  pre_tasks:
    - raw: apt-get install -qq python2.7

  roles:
    - { role: "base" }
    - { role: "master", when: inventory_hostname == masterNodeName }
    - { role: "node", when: inventory_hostname != masterNodeName }
