apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry
  ports:
  - name: registry
    nodePort: 32000
    port: 5000
    protocol: TCP
    targetPort: 5000
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
