---
kind: ReplicationController
apiVersion: v1
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: localhost:32000/hello-world:v1
        ports:
        - name: http-server
          containerPort: 8080
